### PR TITLE
Skurfer v4

### PR DESCRIPTION
**Pull request by pjrobertson**
Changes to make this work with the MAS version of 1Pwd again.

See #6 for more info

### CODE REVIEW

**Comment by skurfer** [comment]
It seems to function correctly. Give me some time to look over the actual code.

Some things I noticed:

  * It looks like you committed `Info.plist` after editing in Xcode, but before `bltrversion` re-rearranged it, so there are a bunch of non-changes getting committed.
  * The change you made to the documentation doesn’t seem to have made it into the plist.
  * What about just showing the actual path in preferences so it’s more compact? Mine doesn’t fit in the window, but I think it would if it were written normally. Maybe also use `~` to shorten it further?

**Comment by pjrobertson** [comment]
For 1 & 2 - yeah I forgot to run bltrversion
For 3 - I agree. The full path doesn’t show for me. Time to remove my beautifying code :’(


I prefer to use encrypted email. You can find my public key here <http://patjack.uk/pk.asc>.
Learn how to encrypt your email with the Email Self Defense Guide <https://emailselfdefense.fsf.org/en/>

**Comment by skurfer** [comment]
The code looks fine to me. The only change I’d add to what was discussed above is that you could probably remove the `viewInOnePwd:` code and the Carbon defines that support it.

**Comment by skurfer** [comment]
You want to transfer this to the organization and I’ll make the changes then release?

**Comment by pjrobertson** [comment]
Good idea, done. Sorry I was slow on this. Flu = stuck in bed feeling sorry for myself ;-)

**Comment by skurfer** [comment]
Thanks. Mostly done, so I put all this on master. I just need to fix the icon. (Maybe the bundle ID changed in v6?)

**Comment by skurfer** [comment]
It’s away! Thanks for the updates and I hope you feel better.

**Comment by pjrobertson** [comment]
> It’s away! Thanks for the updates and I hope you feel better.

Cheers, thanks for all your help on this :-)

**Pull request merged**
